server:
  port: 8443
  ssl:
    key-store: classpath:certificate.p12
    key-store-password: 1234
    key-store-type: PKCS12
    key-alias: tomcat
spring:
  application:
    name: fcss-01
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring
    username: root
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
      data-locations: classpath:data/data.sql
      schema-locations: classpath:data/schema.sql
logging:
  level:
    root: debug